//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPBD2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Soins = new HashSet<Soin>();
            this.Proprietaires = new HashSet<Proprietaire>();
        }
    
        public int ID { get; set; }
        public string Nom { get; set; }
        public Nullable<int> EspeceID { get; set; }
        public string Couleur { get; set; }
        public string Sexe { get; set; }
        public Nullable<int> Poids { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
    
        public virtual Espece Espece { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soin> Soins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proprietaire> Proprietaires { get; set; }
    }
}
